import type { Metadata } from "next";
import { PlaygroundShell } from "@/components/playground/playground-shell";
import { SectionHeading } from "@/components/playground/section-heading";
import { RhythmCircle } from "@/components/playground/rhythm-circle";

export const metadata: Metadata = {
	title: "Rhythm circle",
	description:
		"Euclidean rhythms as an instrument: spread a few pulses evenly around a ring, press play, and hear the tresillo, the bossa nova, the aksak - the timeline patterns of world music, generated by Bjorklund's algorithm. No data feed, no audio files.",
	alternates: { canonical: "/playground/rhythm-circle" },
};

export default function RhythmCirclePage() {
	return (
		<PlaygroundShell
			eyebrow="Playground"
			title="Rhythm circle"
			intro="Every timeline you have tapped along to may be Euclid's algorithm in disguise: spread a few pulses as evenly as possible around a ring and out come the tresillo, the bossa nova, the Turkish aksak. Pick steps and pulses, press play, and hear the math while the circle shows the pattern."
			meta={<>No data feed - the pattern is computed in the page · Rhythms after Toussaint, 2005</>}
		>
			<section aria-label="The instrument">
				<SectionHeading label="The instrument" note="sound on - press play" />
				<RhythmCircle />
			</section>

			<section aria-label="Method and sources">
				<SectionHeading label="Method and sources" />
				<div className="flex max-w-2xl flex-col gap-3 text-copy-13 text-text-faint">
					<p>
						The pattern is Bjorklund&apos;s algorithm: distribute a number of pulses as
						evenly as possible across a number of steps. In 2005, Godfried Toussaint showed
						that the same construction generates the timeline patterns of much of the
						world&apos;s music - the tresillo, the bossa nova clave, the Turkish aksak -
						which is why the preset chips carry their origins. Every named pattern here is
						pinned to the string the paper prints.
					</p>
					<p>
						Nothing is fetched at runtime: this is the playground&apos;s first piece with no
						data feed. The algorithm is the data, computed in your browser, so nothing here
						can go stale. The sound is a Web Audio tick built from an oscillator and a short
						envelope - no audio files; browsers only allow sound after a deliberate gesture,
						which is what the play button is for. With reduced motion enabled, the sweeping
						playhead becomes a discrete step highlight.
					</p>
					<p>
						Rhythms after{" "}
						<a
							href="https://www-cgrl.cs.mcgill.ca/~godfried/publications/banff.pdf"
							target="_blank"
							rel="noreferrer"
							className="text-brand transition-opacity hover:opacity-75"
						>
							Toussaint, 2005
						</a>
						, &quot;The Euclidean Algorithm Generates Traditional Musical Rhythms&quot;,
						Renaissance Banff: Mathematics, Music, Art, Culture, pp. 47-56.
					</p>
				</div>
			</section>
		</PlaygroundShell>
	);
}
