// Antipodes: the point diametrically opposite a place on the Earth, and what
// is actually there. Pure math, mask lookup, and search; no data imports.
// The place table is a committed artifact
// (src/data/playground/antipode-places.json) generated by
// scripts/fetch-antipode-places.mjs; decode it with decodePlaces. The land
// mask is the same committed 1.5-degree grid the night-side map draws
// (src/data/playground/night-side-mask.json); decode it with decodeMaskBits.
//
// Conventions (labeled on the page): spherical Earth, R = 6371.0088 km - the
// same value as great-circle. The surface distance between antipodes is
// always pi * R = 20,015.114 km. The land/ocean reading comes from the same
// 1.5-degree grid the map draws (about 150 km cells); near a coast the
// reading can flip against full-detail geography - measured at build time,
// about 1 in 80 sample places. Nearest place is measured over the committed
// table (7,342 places; tiny settlements may be missing).
// Verified against the vetting pins: roundtrip exact over 2,000 random
// points; distance to the antipode = pi*R everywhere; Wellington ->
// Salamanca 51.8 km; Hancheng -> Malargue 1.3 km; Tehran -> Papeete
// 2,889.5 km.

const D2R = Math.PI / 180;

/** The distance convention labeled on the page (spherical). */
export const EARTH_R_KM = 6371.0088;

/** The surface distance between any two antipodes: pi * R, km. */
export const ANTIPODE_KM = Math.PI * EARTH_R_KM;

/** The Earth's diameter: 2 * R, km - the straight path through the center. */
export const EARTH_D_KM = 2 * EARTH_R_KM;

/** The longest full-load airliner range flown to date (A350-900ULR), km. */
export const LONGEST_RANGE_KM = 18000;

/** The share of the antipode distance the longest-range airliner covers. */
export const LONGEST_RANGE_SHARE = LONGEST_RANGE_KM / ANTIPODE_KM;

/** The local solar time difference between antipodes, hours. */
export const SOLAR_TIME_FLIP_H = 12;

export type Vec3 = [number, number, number];

/** Unit vector for a latitude/longitude pair, degrees. */
export function toVec(lat: number, lon: number): Vec3 {
	const a = lat * D2R;
	const o = lon * D2R;
	return [Math.cos(a) * Math.cos(o), Math.cos(a) * Math.sin(o), Math.sin(a)];
}

/** The central angle between two unit vectors, radians (atan2 form). */
export function centralAngle(a: Vec3, b: Vec3): number {
	const cx = a[1] * b[2] - a[2] * b[1];
	const cy = a[2] * b[0] - a[0] * b[2];
	const cz = a[0] * b[1] - a[1] * b[0];
	return Math.atan2(Math.hypot(cx, cy, cz), a[0] * b[0] + a[1] * b[1] + a[2] * b[2]);
}

/** Great-circle distance between two unit vectors, km. */
export function distanceKm(a: Vec3, b: Vec3): number {
	return centralAngle(a, b) * EARTH_R_KM;
}

/** Great-circle distance between two latitude/longitude points, km. */
export function distanceLatLonKm(lat1: number, lon1: number, lat2: number, lon2: number): number {
	return distanceKm(toVec(lat1, lon1), toVec(lat2, lon2));
}

/** Normalize a longitude to [-180, 180). */
export function norm180(lon: number): number {
	return ((lon + 540) % 360) - 180;
}

/** The antipode of a point: the exact other side of the Earth. */
export function antipode(lat: number, lon: number): { lat: number; lon: number } {
	return { lat: -lat, lon: norm180(lon + 180) };
}

// --- The land mask (the night-side grid: 1.5 degrees, 240x120, one bit per
// cell, LSB-first within each byte, row-major from the north pole).

/** Decode the committed base64 bitmask (works in browsers and node). */
export function decodeMaskBits(b64: string): Uint8Array {
	const bin = atob(b64);
	const bytes = new Uint8Array(bin.length);
	for (let i = 0; i < bin.length; i += 1) bytes[i] = bin.charCodeAt(i);
	return bytes;
}

export interface MaskGrid {
	step: number;
	cols: number;
	rows: number;
}

/**
 * Is the grid cell containing (lat, lon) land? Single-cell lookup, clamped
 * at the poles and the antimeridian - the same cell the map draws.
 */
export function maskLandAt(bytes: Uint8Array, grid: MaskGrid, lat: number, lon: number): boolean {
	const i = Math.min(grid.cols - 1, Math.max(0, Math.floor((lon + 180) / grid.step)));
	const j = Math.min(grid.rows - 1, Math.max(0, Math.floor((90 - lat) / grid.step)));
	const bit = j * grid.cols + i;
	return ((bytes[bit >> 3] >> (bit & 7)) & 1) === 1;
}

// --- The place table.

/** The artifact's row shape: [name, country, lat, lon, pop]. */
export type PlaceRow = [string, string, number, number, number | null];

export interface Place {
	name: string;
	country: string;
	lat: number;
	lon: number;
	/** Population; null or <= 0 reads as unknown (10 rows in the source). */
	pop: number | null;
}

/** The committed table's document shape (src/data/playground). */
export interface AntipodeTable {
	source: string;
	sourceUrl: string;
	license: string;
	licenseUrl: string;
	fetched: string;
	sourceSha256: string;
	fields: string[];
	count: number;
	places: PlaceRow[];
}

/** Expand the artifact's array-per-row shape into objects. */
export function decodePlaces(rows: readonly PlaceRow[]): Place[] {
	return rows.map(([name, country, lat, lon, pop]) => ({ name, country, lat, lon, pop }));
}

// --- Nearest place and ranked search.

export interface NearestPlace {
	place: Place;
	km: number;
}

/** The nearest place to a point, over the whole table (7,342 rows). */
export function nearestPlace(places: readonly Place[], lat: number, lon: number): NearestPlace | null {
	const v = toVec(lat, lon);
	let best: Place | null = null;
	let bestKm = Infinity;
	for (const p of places) {
		const km = distanceKm(v, toVec(p.lat, p.lon));
		if (km < bestKm) {
			bestKm = km;
			best = p;
		}
	}
	return best ? { place: best, km: bestKm } : null;
}

/** Lowercased, diacritic-stripped form used on both sides of a match. */
export function normalizeQuery(input: string): string {
	return input
		.normalize("NFD")
		.replace(/[\u0300-\u036f]/g, "")
		.toLowerCase()
		.replace(/[\u2018\u2019']/g, "")
		.trim();
}

/** Ranking weight for a population: unknown (null or <= 0) sorts last. */
function popRank(pop: number | null): number {
	return pop !== null && pop > 0 ? pop : -1;
}

/**
 * Ranked matches: name exact, country exact (typing a country browses its
 * places), name prefix, name contains, country prefix; ties by population
 * (unknown last). Empty query matches nothing. Results carry the country so
 * duplicate names stay distinguishable.
 */
export function searchPlaces(places: readonly Place[], query: string, limit = 8): Place[] {
	const q = normalizeQuery(query);
	if (q.length === 0) return [];
	const scored: { rank: number; pop: number; place: Place }[] = [];
	for (const place of places) {
		const name = normalizeQuery(place.name);
		const country = normalizeQuery(place.country);
		let rank = -1;
		if (name === q) rank = 0;
		else if (country === q) rank = 1;
		else if (name.startsWith(q)) rank = 2;
		else if (name.includes(q)) rank = 3;
		else if (country.startsWith(q)) rank = 4;
		if (rank !== -1) scored.push({ rank, pop: popRank(place.pop), place });
	}
	scored.sort((a, b) => (a.rank !== b.rank ? a.rank - b.rank : b.pop - a.pop));
	return scored.slice(0, limit).map((s) => s.place);
}

// --- Display helpers for the readout.

/** "1.3 km" / "2,889.5 km" - one decimal, thousands separators. */
export function formatKm(km: number): string {
	const n = new Intl.NumberFormat("en-US", {
		minimumFractionDigits: 1,
		maximumFractionDigits: 1,
	}).format(km);
	return `${n} km`;
}

/** "35.7S, 128.6W" - one decimal, hemisphere letters. */
export function formatLatLon(lat: number, lon: number): string {
	const la = `${Math.abs(lat).toFixed(1)}${lat >= 0 ? "N" : "S"}`;
	const lo = `${Math.abs(lon).toFixed(1)}${lon >= 0 ? "E" : "W"}`;
	return `${la}, ${lo}`;
}

/** "132k" / "7.9M" / "unknown" - compact population for labels. */
export function formatPop(pop: number | null): string {
	if (pop === null || pop <= 0) return "unknown";
	if (pop >= 1e6) return `${(pop / 1e6).toFixed(1)}M`;
	if (pop >= 1e3) return `${Math.round(pop / 1e3)}k`;
	return `${pop}`;
}
