// Color vision: simulate protanomaly / deuteranomaly / tritanomaly on any
// color, using the Machado, Oliveira & Fernandes 2009 model - the modern
// reference model for color vision deficiency, covering anomalous trichromacy
// (partial, the common case) and dichromacy (complete) in one framework.
// Pure math; no data imports. The 33 precomputed matrices (severities
// 0.0-1.0 step 0.1 x protanomaly / deuteranomaly / tritanomaly) are a
// committed artifact (src/data/playground/cvd-matrices.json) generated by
// scripts/fetch-cvd-matrices.mjs; decode it with decodeCvdMatrices.
//
// Conventions (labeled on the page): matrices are applied in linear RGB
// (sRGB decoded first); severity = floor to the 0.1 grid plus a linear blend
// of the adjacent pair - the interpolation the authors' page teaches.
// Verified against the authors' published anchors in the lab's vetting
// probes (deutan 1.0: red -> #A39000, green -> #EFD63A; protan 1.0 red ->
// #6D5F00; tritan 1.0 green -> #00F7D9; severity 0.0 is the identity; the
// authors' 0.873 example reproduces the 0.27/0.73 blend).
//
// Model edge (labeled in the copy): protanomaly / deuteranomaly at severity
// 1.0 approximate complete dichromacy, but tritanomaly 1.0 is the model's
// own maximum, not tritanopia - the model restrains tritan by design.

export const CVD_TYPES = ["protan", "deutan", "tritan"] as const;

export type CvdType = (typeof CVD_TYPES)[number];

/** An RGB triple, each channel 0-1 (sRGB, non-linear). */
export type Rgb = [number, number, number];

/** The committed table's shape (src/data/playground/cvd-matrices.json). */
export interface CvdMatricesDoc {
	source: string;
	sourceUrl: string;
	doi: string;
	license: string;
	fetched: string;
	sourceSha256: string;
	convention: string;
	severityStep: number;
	/** 11 flat 3x3 matrices per type; index = severity / severityStep. */
	types: Record<CvdType, number[][]>;
}

/** The three types' matrix lists (what the simulation functions take). */
export type CvdMatrices = CvdMatricesDoc["types"];

/** Validate the committed table's shape; throws on anything malformed. */
export function decodeCvdMatrices(doc: CvdMatricesDoc): CvdMatricesDoc {
	const types = doc.types as Record<CvdType, unknown>;
	for (const type of CVD_TYPES) {
		const list = types[type];
		if (!Array.isArray(list) || list.length !== 11) {
			throw new Error(`cvd matrices: ${type} needs 11 severities`);
		}
		for (const m of list) {
			if (!Array.isArray(m) || m.length !== 9 || m.some((v) => !Number.isFinite(v))) {
				throw new Error(`cvd matrices: malformed 3x3 in ${type}`);
			}
		}
	}
	return doc;
}

export function clamp01(v: number): number {
	return Math.min(1, Math.max(0, v));
}

/** An sRGB channel (0-1) -> linear light. */
export function srgbToLinear(c: number): number {
	return c <= 0.04045 ? c / 12.92 : Math.pow((c + 0.055) / 1.055, 2.4);
}

/** A linear-light channel -> sRGB (0-1). */
export function linearToSrgb(c: number): number {
	return c <= 0.0031308 ? 12.92 * c : 1.055 * Math.pow(c, 1 / 2.4) - 0.055;
}

/** #RGB or #RRGGBB (with or without #) -> floats 0-1. */
export function hexToRgb(hex: string): Rgb {
	const h = hex.replace(/^#/, "");
	const full = h.length === 3 ? h.split("").map((c) => c + c).join("") : h;
	if (!/^[0-9a-fA-F]{6}$/.test(full)) throw new Error(`unparseable hex: ${hex}`);
	const n = Number.parseInt(full, 16);
	return [((n >> 16) & 255) / 255, ((n >> 8) & 255) / 255, (n & 255) / 255];
}

/** Floats 0-1 -> uppercase #RRGGBB (channels clamped for display). */
export function rgbToHex(rgb: Rgb): string {
	const c = (v: number) => Math.round(clamp01(v) * 255).toString(16).padStart(2, "0");
	return `#${c(rgb[0])}${c(rgb[1])}${c(rgb[2])}`.toUpperCase();
}

/**
 * The flat 3x3 for a type at a severity 0-1: floor to the 0.1 grid, then
 * blend the adjacent pair (the authors' interpolation; 0.873 -> the 0.8 and
 * 0.9 matrices at weight 0.73).
 */
export function matrixFor(matrices: CvdMatrices, type: CvdType, severity: number): number[] {
	const t = clamp01(severity) * 10;
	const i = Math.min(9, Math.floor(t));
	const w = t - i;
	const m1 = matrices[type][i];
	const m2 = matrices[type][i + 1];
	return m1.map((v, k) => v * (1 - w) + m2[k] * w);
}

/**
 * Apply a flat 3x3 in linear RGB (sRGB decode first); returns sRGB floats,
 * unclamped - callers clamp for display (browsers clamp too).
 */
export function applyCvdMatrix(m: readonly number[], rgb: Rgb): Rgb {
	const [r, g, b] = rgb.map(srgbToLinear);
	const o0 = m[0] * r + m[1] * g + m[2] * b;
	const o1 = m[3] * r + m[4] * g + m[5] * b;
	const o2 = m[6] * r + m[7] * g + m[8] * b;
	return [linearToSrgb(o0), linearToSrgb(o1), linearToSrgb(o2)];
}

/** The simulated color of an sRGB float triple. */
export function simulateRgb(matrices: CvdMatrices, rgb: Rgb, type: CvdType, severity: number): Rgb {
	return applyCvdMatrix(matrixFor(matrices, type, severity), rgb);
}

/** The simulated color of a hex color, as uppercase hex. */
export function simulateHex(matrices: CvdMatrices, hex: string, type: CvdType, severity: number): string {
	return rgbToHex(simulateRgb(matrices, hexToRgb(hex), type, severity));
}

/**
 * oklch -> sRGB floats (Ottosson's conversion; the pipeline for the
 * self-generated spectrum - runtime token values come from canvas readback
 * instead). May land out of gamut; callers clamp for display.
 */
export function oklchToSrgb(L: number, C: number, H: number): Rgb {
	const h = (H * Math.PI) / 180;
	const a = C * Math.cos(h);
	const b = C * Math.sin(h);
	const l_ = L + 0.3963377774 * a + 0.2158037573 * b;
	const m_ = L - 0.1055613458 * a - 0.0638541728 * b;
	const s_ = L - 0.0894841775 * a - 1.291485548 * b;
	const l = l_ ** 3;
	const m = m_ ** 3;
	const s = s_ ** 3;
	const o0 = 4.0767416621 * l - 3.3077115913 * m + 0.2309699292 * s;
	const o1 = -1.2684380046 * l + 2.6097574011 * m - 0.3413193965 * s;
	const o2 = -0.0041960863 * l - 0.7034186147 * m + 1.707614701 * s;
	return [linearToSrgb(o0), linearToSrgb(o1), linearToSrgb(o2)];
}

/** oklch -> uppercase hex (clamped). */
export function oklchToHex(L: number, C: number, H: number): string {
	return rgbToHex(oklchToSrgb(L, C, H));
}
