// --- Playground: free shelf parsing ---
// Pure functions behind the free shelf source: entity decode, dash
// normalization, the chart-page parse, and validation of the committed
// snapshot. Type-only imports, so node can load this module directly for
// checks; scripts/fetch-free-shelf-snapshot.mjs mirrors the same parse.
//
// Source note (2026-10-08): Project Gutenberg's Apache negotiates by Accept
// header. Browsers (Accept: text/html) get the static, daily-regenerated
// top.html; clients sending Accept: * / * get a legacy top.php variant with a
// broken stats table and different counts. The page and its snapshot script
// both send Accept: text/html to read the same page a visitor would see.

import type { FreeShelfBook, FreeShelfData, FreeShelfWindowKey } from "@/lib/playground/types";

export const WINDOW_KEYS: FreeShelfWindowKey[] = ["last1", "last7", "last30"];

/** The snapshot carries 30 per window; the page displays the top 20. */
export const PER_WINDOW = 30;
/** Below this many parsed items in any window, the page falls back. */
export const MIN_PER_WINDOW = 20;

function codePoint(n: number): string {
	if (!Number.isFinite(n) || n < 0 || n > 0x10ffff) return "";
	try {
		return String.fromCodePoint(n);
	} catch {
		return "";
	}
}

/**
 * Decode the entities the chart page carries, then normalize PG's own
 * punctuation: em/en dashes (raw characters and entity forms) become ASCII
 * hyphens, per the site rule. Whitespace collapses.
 */
export function decodeEntities(input: string): string {
	return input
		.replace(/&amp;/g, "&")
		.replace(/&lt;/g, "<")
		.replace(/&gt;/g, ">")
		.replace(/&quot;/g, '"')
		.replace(/&apos;/g, "'")
		.replace(/&nbsp;/g, " ")
		.replace(/&#(\d+);/g, (_, d) => codePoint(Number(d)))
		.replace(/&#x([0-9a-fA-F]+);/g, (_, h) => codePoint(parseInt(h, 16)))
		.replace(/[\u2013\u2014]/g, "-")
		.replace(/\s+/g, " ")
		.trim();
}

/** Validate one parsed or stored book entry; null when unusable. */
export function toBook(raw: unknown): FreeShelfBook | null {
	const book = (raw ?? {}) as { id?: unknown; title?: unknown; author?: unknown; downloads?: unknown };
	if (typeof book.id !== "number" || !Number.isInteger(book.id) || book.id <= 0) return null;
	if (typeof book.title !== "string" || book.title === "") return null;
	const author = typeof book.author === "string" && book.author !== "" ? book.author : null;
	if (typeof book.downloads !== "number" || !Number.isInteger(book.downloads) || book.downloads < 0) {
		return null;
	}
	return { id: book.id, title: book.title, author, downloads: book.downloads };
}

/**
 * Parse the three chart sections out of the chart page's HTML. Throws when a
 * section cannot be found or parses fewer than MIN_PER_WINDOW usable items,
 * so the caller can fall back to the committed snapshot.
 */
export function parseChartSections(html: string): Record<FreeShelfWindowKey, FreeShelfBook[]> {
	const sections = {} as Record<FreeShelfWindowKey, FreeShelfBook[]>;
	for (const key of WINDOW_KEYS) {
		const start = html.indexOf(`<h2 id="books-${key}">`);
		const olStart = start < 0 ? -1 : html.indexOf("<ol>", start);
		const olEnd = olStart < 0 ? -1 : html.indexOf("</ol>", olStart);
		if (start < 0 || olStart < 0 || olEnd < 0) {
			throw new Error(`free-shelf chart: section ${key} not found`);
		}
		const chunk = html.slice(olStart, olEnd);
		const items: FreeShelfBook[] = [];
		const re = /<li><a href="\/ebooks\/(\d+)">(.+?)<\/a><\/li>/g;
		let m: RegExpExecArray | null;
		while ((m = re.exec(chunk))) {
			const id = Number(m[1]);
			const label = decodeEntities(m[2]);
			const mCount = / \((\d+)\)$/.exec(label);
			const downloads = mCount ? Number(mCount[1]) : null;
			const core = mCount ? label.slice(0, mCount.index) : label;
			const mBy = /^(.*?) by (.+)$/.exec(core);
			const book = toBook({
				id,
				title: mBy ? mBy[1] : core,
				author: mBy ? mBy[2] : null,
				downloads,
			});
			if (book) items.push(book);
		}
		if (items.length < MIN_PER_WINDOW) {
			throw new Error(`free-shelf chart: section ${key} parsed ${items.length} usable items`);
		}
		sections[key] = items;
	}
	return sections;
}

/**
 * Validate the committed snapshot JSON into the page's data shape. The
 * snapshot is generated by scripts/fetch-free-shelf-snapshot.mjs; a broken
 * one should fail loudly at check time, never render as empty.
 */
export function snapshotToData(raw: unknown): FreeShelfData {
	const doc = (raw ?? {}) as { fetched?: unknown; chartModified?: unknown; windows?: unknown };
	if (typeof doc.fetched !== "string") throw new Error("free-shelf snapshot: fetched missing");
	const windowsRaw = (doc.windows ?? {}) as Record<string, unknown>;
	const windows = {} as Record<FreeShelfWindowKey, FreeShelfBook[]>;
	for (const key of WINDOW_KEYS) {
		const list = windowsRaw[key];
		if (!Array.isArray(list)) throw new Error(`free-shelf snapshot: window ${key} missing`);
		const books = list.map(toBook).filter((book): book is FreeShelfBook => book !== null);
		if (books.length < MIN_PER_WINDOW) {
			throw new Error(`free-shelf snapshot: window ${key} has ${books.length} usable items`);
		}
		windows[key] = books.slice(0, PER_WINDOW);
	}
	return {
		asOf: doc.fetched,
		chartModified: typeof doc.chartModified === "string" ? doc.chartModified : null,
		provenance: "snapshot",
		windows,
	};
}
