// Great circle: the shortest path between two points on a sphere, and the two
// ways the piece draws it - the flat map, where the path bows, and the globe,
// where the same path is straight. Pure math and search; no data imports. The
// airport table is a committed artifact
// (src/data/playground/great-circle-airports.json) generated by
// scripts/fetch-great-circle-data.mjs; decode it with decodeAirports.
//
// Conventions (labeled on the page): spherical Earth, R = 6371.0088 km - the
// value that matches gcmap-style published distances; flight time =
// distance / 850 km/h + 30 min, an estimate. Verified against published
// landmarks in the lab's vetting probes (JFK-LHR 5,539.8 vs 5,540; SYD-LAX
// 12,061.2 vs 12,061; farthest scheduled pair 20,012 km).

const D2R = Math.PI / 180;
const R2D = 180 / Math.PI;

/** The distance convention labeled on the page (spherical). */
export const EARTH_R_KM = 6371.0088;

/** 2 pi R; the circumference share is measured against this. */
export const EARTH_CIRCUMFERENCE_KM = 2 * Math.PI * EARTH_R_KM;

/** The time model's cruise speed, km/h (labeled estimate). */
export const CRUISE_KMH = 850;

/** The time model's fixed taxi allowance, minutes (labeled estimate). */
export const TAXI_MIN = 30;

export type Vec3 = [number, number, number];

/** Unit vector for a latitude/longitude pair, degrees. */
export function toVec(lat: number, lon: number): Vec3 {
	const a = lat * D2R;
	const o = lon * D2R;
	return [Math.cos(a) * Math.cos(o), Math.cos(a) * Math.sin(o), Math.sin(a)];
}

function dot3(a: Vec3, b: Vec3): number {
	return a[0] * b[0] + a[1] * b[1] + a[2] * b[2];
}

function cross3(a: Vec3, b: Vec3): Vec3 {
	return [a[1] * b[2] - a[2] * b[1], a[2] * b[0] - a[0] * b[2], a[0] * b[1] - a[1] * b[0]];
}

function norm3(a: Vec3): Vec3 {
	const n = Math.hypot(a[0], a[1], a[2]);
	return [a[0] / n, a[1] / n, a[2] / n];
}

/** The central angle between two unit vectors, radians (atan2 form). */
export function centralAngle(a: Vec3, b: Vec3): number {
	const c = cross3(a, b);
	return Math.atan2(Math.hypot(c[0], c[1], c[2]), dot3(a, b));
}

/** Great-circle distance between two unit vectors, km. */
export function distanceKm(a: Vec3, b: Vec3): number {
	return centralAngle(a, b) * EARTH_R_KM;
}

/** The point at fraction t (0-1) along the great circle from a to b (slerp). */
export function slerp(a: Vec3, b: Vec3, t: number): Vec3 {
	const d = centralAngle(a, b);
	const s = Math.sin(d);
	if (s < 1e-12) return [a[0], a[1], a[2]]; // same point (or exactly antipodal)
	const u = Math.sin((1 - t) * d) / s;
	const v = Math.sin(t * d) / s;
	return [a[0] * u + b[0] * v, a[1] * u + b[1] * v, a[2] * u + b[2] * v];
}

/** Points along the path from a to b, inclusive (segments + 1 points). */
export function pathPoints(a: Vec3, b: Vec3, segments: number): Vec3[] {
	const pts: Vec3[] = [];
	for (let i = 0; i <= segments; i += 1) pts.push(slerp(a, b, i / segments));
	return pts;
}

/** Latitude/longitude, degrees, of a unit vector. */
export function toLatLon(p: Vec3): { lat: number; lon: number } {
	return {
		lat: Math.asin(Math.max(-1, Math.min(1, p[2]))) * R2D,
		lon: Math.atan2(p[1], p[0]) * R2D,
	};
}

/** The path's midpoint; for near-antipodal pairs any 90-degree point works. */
export function midpoint(a: Vec3, b: Vec3): Vec3 {
	const s: Vec3 = [a[0] + b[0], a[1] + b[1], a[2] + b[2]];
	const n = Math.hypot(s[0], s[1], s[2]);
	if (n > 1e-6) return [s[0] / n, s[1] / n, s[2] / n];
	const axis: Vec3 = Math.abs(a[0]) < 0.9 ? [1, 0, 0] : [0, 1, 0];
	return norm3(cross3(a, axis));
}

// --- The flat map (equirectangular): lon/lat to canvas pixels.

/** Flat map x for a longitude, in px (the canvas spans the full world). */
export function flatX(lon: number, w: number): number {
	return ((lon + 180) / 360) * w;
}

/** Flat map y for a latitude, in px (the canvas spans the full world). */
export function flatY(lat: number, h: number): number {
	return ((90 - lat) / 180) * h;
}

/**
 * Longitudes made continuous (each step under 180 degrees) so a flat
 * polyline crossing the antimeridian does not jump the map edge. Draw the
 * polyline and its +/-360-degree copies to cover both edges.
 */
export function unwrapLons(lons: number[]): number[] {
	const out = lons.slice();
	for (let i = 1; i < out.length; i += 1) {
		while (out[i] - out[i - 1] > 180) out[i] -= 360;
		while (out[i] - out[i - 1] < -180) out[i] += 360;
	}
	return out;
}

// --- The globe: a tangent-plane projection centered on the route midpoint.

export interface GlobePoint {
	/** Offset from the globe center, px. */
	x: number;
	y: number;
	/** True when the point is on the visible hemisphere. */
	front: boolean;
}

/**
 * Project a unit vector for a globe centered on `center` (north up). A great
 * circle through the center projects to a straight line; that is the point of
 * the second view.
 */
export function globePoint(p: Vec3, center: Vec3, radius: number): GlobePoint {
	let right = cross3([0, 0, 1], center);
	if (Math.hypot(right[0], right[1], right[2]) < 1e-6) {
		right = cross3([0, 1, 0], center); // center at a pole: any stable roll
	}
	right = norm3(right);
	const up = cross3(center, right);
	return {
		x: dot3(p, right) * radius,
		y: -dot3(p, up) * radius,
		front: dot3(p, center) > 0,
	};
}

// --- The airport table.

/** The artifact's row shape: [iata, name, city, cc, lat, lon]. */
export type AirportRow = [string, string, string, string, number, number];

export interface Airport {
	iata: string;
	name: string;
	city: string;
	cc: string;
	lat: number;
	lon: number;
}

/** The committed table's document shape (src/data/playground). */
export interface GreatCircleTable {
	source: string;
	sourceUrl: string;
	license: string;
	licenseUrl: string;
	fetched: string;
	sourceSha256: string;
	sourceLastModified: string;
	fields: string[];
	count: number;
	farthestPair: { a: string; b: string; km: number };
	airports: AirportRow[];
}

/** Expand the artifact's array-per-row shape into objects. */
export function decodeAirports(rows: readonly AirportRow[]): Airport[] {
	return rows.map(([iata, name, city, cc, lat, lon]) => ({ iata, name, city, cc, lat, lon }));
}

// --- Search: one field over code, city, and name.

/** Lowercased, diacritic-stripped form used on both sides of a match. */
export function normalizeQuery(input: string): string {
	return input
		.toLowerCase()
		.normalize("NFD")
		.replace(/[\u0300-\u036f]/g, "")
		.trim();
}

/**
 * Ranked matches: code exact, code prefix, city prefix, name prefix, then
 * city/name contains; ties by code. Empty query matches nothing.
 */
export function searchAirports(airports: readonly Airport[], query: string, limit = 8): Airport[] {
	const q = normalizeQuery(query);
	if (q.length === 0) return [];
	const scored: { rank: number; airport: Airport }[] = [];
	for (const airport of airports) {
		const code = airport.iata.toLowerCase();
		const city = normalizeQuery(airport.city);
		const name = normalizeQuery(airport.name);
		let rank = -1;
		if (code === q) rank = 0;
		else if (code.startsWith(q)) rank = 1;
		else if (city.startsWith(q)) rank = 2;
		else if (name.startsWith(q)) rank = 3;
		else if (city.includes(q)) rank = 4;
		else if (name.includes(q)) rank = 5;
		if (rank !== -1) scored.push({ rank, airport });
	}
	scored.sort((a, b) => (a.rank !== b.rank ? a.rank - b.rank : a.airport.iata < b.airport.iata ? -1 : 1));
	return scored.slice(0, limit).map((s) => s.airport);
}

// --- Display helpers for the readout.

/** The labeled flight-time estimate for a distance: km / 850 km/h + 30 min. */
export function estimateFlightMinutes(km: number): number {
	return Math.round((km / CRUISE_KMH) * 60) + TAXI_MIN;
}

/** "7 h 01 min" style duration from whole minutes. */
export function formatDuration(minutes: number): string {
	const h = Math.floor(minutes / 60);
	const m = minutes % 60;
	return `${h} h ${String(m).padStart(2, "0")} min`;
}

/** "5,539.8 km" - one decimal, thousands separators. */
export function formatKm(km: number): string {
	const n = new Intl.NumberFormat("en-US", {
		minimumFractionDigits: 1,
		maximumFractionDigits: 1,
	}).format(km);
	return `${n} km`;
}

/** The distance as a share of Earth's circumference: "14%", "0.1%". */
export function formatShare(km: number): string {
	const pct = (km / EARTH_CIRCUMFERENCE_KM) * 100;
	return pct >= 10 ? `${Math.round(pct)}%` : `${pct.toFixed(1)}%`;
}
